Repository KendallDoesCoding/youtubers-birthdays, pull requests merged in 2023-04, with the labels that each got.

#18 Updated index.html
  index.html
Labels: size/XS

#19 added total youtuber count and currentPage in pagination
  index.html
  index.js
  styles.css
Labels: size/M

#21 Add CONTRIBUTING Guidelines and Code Of Conduct
  .github/CONTRIBUTING.md
  CODE_OF_CONDUCT.md
  README.md
Labels: documentation, size/L

#24 add youtuber
  index.html
Labels: size/XS

#25 Added the search bar
  index.html
  index.js
  styles.css
Labels: size/L

#26 Added YouTubers to the index.html
  index.html
  list-to-add.txt
  styles.css
Labels: size/L

#29 Fixed Documentation Issue
  index.js
Labels: size/XS

#28 adding slayy point youtube channel
  index.html
Labels: size/S

#31 Added a tech youtuber to the table in index.html
  index.html
Labels: size/XS

#32 added macie jay yt
  index.html
Labels: size/XS
