Repository KendallDoesCoding/youtubers-birthdays, pull requests merged in 2023-06, with the labels that each got.

#39 new youtuber added
  index.html
Labels: size/XS

#40 Update index.html
  index.html
Labels: size/XS

#41 Add 3 new youtubers
  index.html
Labels: size/S

#42 chore: update birthday format
  .github/CONTRIBUTING.md
  index.html
Labels: size/L

#35 added youtuber
  index.html
Labels: size/XS

#38 added more youtubers
  index.html
Labels: size/S

#47 Newnamesintothelist
  list-to-add.txt
Labels: size/S

#49 Added youtuber
  index.html
Labels: size/S

#50 chore: update the views counter to approx views from June.
  index.html
Labels: size/L
