Repository KendallDoesCoding/youtubers-birthdays, pull requests merged in 2023-08, with the labels that each got.

#51 myler fam members
  index.html
Labels: size/S

#58 chore: add youtube logo on page.
  index.html
  styles.css
Labels: size/S

#59 added IShowspeed to the names list
  index.html
Labels: size/XS

#67 chore: update README.md
  README.md
Labels: size/S

#69 fix: birthday date format
  models/youtuber-model.js
  views/home.ejs
Labels: size/S

#70 feat: update views after every new entry in list
  package-lock.json
  package.json
  server.js
  updateView.js
Labels: size/M

#73 feat: add Daily Max to the list.
  README.md
Labels: size/L
