Repository KendallDoesCoding/youtubers-birthdays, pull requests merged in 2023-09, with the labels that each got.

#78 Update README.md
  README.md
Labels: size/XS

#72 small update the contributing guidelines
  .github/CONTRIBUTING.md
Labels: size/XS

#85 add Aman to the list.
  README.md
Labels: size/XS

#86 add flying beast
  README.md
Labels: size/XS

#89 add BeerBiceps
  README.md
Labels: size/XS

#91 add CarryisLive
  README.md
Labels: size/XS

#77 fixes: #76bug add validation for all input field's
  package-lock.json
  package.json
  public/index.js
  public/styles.css
  public/validation.js
  views/addYoutuber.ejs
Labels: size/L

#93 add MortaL
  README.md
Labels: size/XS

#95 added button for adding youtuber
  public/styles.css
  views/home.ejs
Labels: size/S

#96 [Fix]:Button bug when click outside of the text button not working.
  public/styles.css
  views/home.ejs
Labels: size/S

#97 Revert "[Fix]:Button bug when click outside of the text button not working."
  public/styles.css
  views/home.ejs
Labels: size/S

#83 [Enhancement ✨]-Restyled the Homepage and Add/Remove-Youtuber pages
  public/styles.css
  views/addYoutuber.ejs
  views/home.ejs
  views/removeYoutuber.ejs
Labels: size/L
